import { Ref, ref } from "vue";

export interface Unite {
  id: number;
  name: string;
  influence: number;
  type: string; // "Mélée" | "Arbalétrier";
  pict: string;
  rarity: string; // "rustic" | "chivalric" | "silver" | "heroic" | "golden";
}

export const state: Ref<Unite[]> = ref([
  {
    id: 0,
    name: "Martellatori",
    influence: 30,
    type: "Mélée",
    pict: "martella.png",
    rarity: "rustic",
    inCaserne: 0,
  },
  {
    id: 1,
    name: "Piquiers de milice",
    influence: 110,
    type: "Piquiers",
    pict: "pk_mil_pre.png",
    rarity: "chivalric",
    inCaserne: 0,
  },
  {
    id: 2,
    name: "Hallebardiers",
    influence: 175,
    type: "Arme d'hast",
    pict: "halb_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 3,
    name: "Piquiers du Dragon noir",
    influence: 120,
    type: "Piquiers",
    pict: "bla_drag_pike.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 4,
    name: "Piquiers préfectoraux",
    influence: 185,
    type: "Piquiers",
    pict: "pref_pike_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 5,
    name: "Gardes préfectoraux",
    influence: 180,
    type: "Mélée",
    pict: "pref_guar_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 6,
    name: "Lanciers du Dragon noir",
    influence: 110,
    type: "Lanciers",
    pict: "bla_drag_spear.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 7,
    name: "Lanciers tête-de-fer",
    influence: 175,
    type: "Lanciers",
    pict: "iro_spear_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 8,
    name: "Javeliniers du Dragon noir",
    influence: 115,
    type: "Javeliniers",
    pict: "bla_drag_jav.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 9,
    name: "Pyro-archers",
    influence: 180,
    type: "Archers",
    pict: "ind_arc_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 10,
    name: "Arbalétriers d'avant-garde",
    influence: 180,
    type: "Arbalétriers",
    pict: "dem_arb_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 11,
    name: "Archers d'avant-garde",
    influence: 160,
    type: "Archers",
    pict: "van_arc_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 12,
    name: "Archers préfectoraux",
    influence: 185,
    type: "Archers",
    pict: "pref_arc_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 13,
    name: "Arquebusiers de domaine",
    influence: 200,
    type: "Arquebusiers",
    pict: "dem_arqu_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 14,
    name: "Ecuyers",
    influence: 170,
    type: "Mélée",
    pict: "squires_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 15,
    name: "Archers vipères",
    influence: 165,
    type: "Archers",
    pict: "ratt_vip_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 16,
    name: "Maîtres de la chu ko nu",
    influence: 180,
    type: "Arbalétriers",
    pict: "ratt_mar_pre.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 17,
    name: "Prévôts hallebardiers",
    influence: 230,
    type: "Arme d'hast",
    pict: "halb_serg_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 18,
    name: "Piquiers impériaux",
    influence: 240,
    type: "Piquiers",
    pict: "imp_pk_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 19,
    name: "Gardes du palais",
    influence: 235,
    type: "Mélée",
    pict: "pala_guar_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 20,
    name: "Lanciers impériaux",
    influence: 245,
    type: "Lanciers",
    pict: "imp_spea_guar_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 21,
    name: "Prévôts javeliniers",
    influence: 230,
    type: "Javeliniers",
    pict: "jav_serg_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 22,
    name: "Javeliniers impériaux",
    influence: 240,
    type: "Javeliniers",
    pict: "imp_jav_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 23,
    name: "Archers gallos",
    influence: 245,
    type: "Archers",
    pict: "vas_long_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 24,
    name: "Archers impériaux",
    influence: 255,
    type: "Archers",
    pict: "imp_arc_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 25,
    name: "Arquebusiers du Kriegsrat",
    influence: 255,
    type: "Armes à feu",
    pict: "krieg_fus_post.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 26,
    name: "Arquebusiers impériaux",
    influence: 255,
    type: "Armes à feu",
    pict: "imp_arq_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 27,
    name: "Yeomen",
    influence: 240,
    type: "Cavalerie",
    pict: "yeom_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 28,
    name: "Cavaliers lourds préfectoraux",
    influence: 240,
    type: "Cavalerie",
    pict: "pre_hea_cav_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 29,
    name: "Lanciers avec esponton",
    influence: 240,
    type: "Cavalerie",
    pict: "dag_axe_lan_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 30,
    name: "Prévôts lanciers",
    influence: 250,
    type: "Lanciers",
    pict: "spe_sarg_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 31,
    name: "Hommes d'armes",
    influence: 240,
    type: "Mélée",
    pict: "men_at_arms_pre.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 32,
    name: "Fauchefers",
    influence: 315,
    type: "Mélée",
    pict: "ir_rea_pre.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 33,
    name: "Arbalétriers pavoiseurs",
    influence: 325,
    type: "Arbalétriers",
    pict: "pavi_cros.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 34,
    name: "Arquebusiers tercios",
    influence: 310,
    type: "Armes à feu",
    pict: "tercio.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 35,
    name: "Cataphractaires lanciers",
    influence: 310,
    type: "Cavalerie",
    pict: "cata_lan_pre.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 36,
    name: "Hussards ailés",
    influence: 315,
    type: "Cavalerie",
    pict: "win_hus_pre.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 37,
    name: "Pyro-lanciers",
    influence: 305,
    type: "Cavalerie",
    pict: "fire_lan_pre.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 38,
    name: "Templiers",
    influence: 305,
    type: "Cavalerie",
    pict: "mona_kni.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 39,
    name: "Maîtres de la chu ko nu montés",
    influence: 305,
    type: "Cavalerie",
    pict: "ratt_ran_pre.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 40,
    name: "Archers de Namkhan",
    influence: 180,
    type: "Archers",
    pict: "nam_arch.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 41,
    name: "Pionniers de Selem",
    influence: 170,
    type: "Cavalerie",
    pict: "selem_cav.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 42,
    name: "Khorchins",
    influence: 170,
    type: "Cavalerie",
    pict: "khorchins.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 43,
    name: "Tseregs",
    influence: 240,
    type: "Mélée",
    pict: "tseregs.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 44,
    name: "Cavaliers kevthuuls",
    influence: 245,
    type: "Cavalerie",
    pict: "khev_cav.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 45,
    name: "Gardes kheshigs",
    influence: 310,
    type: "Cavalerie",
    pict: "kheshigs.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 46,
    name: "Condottières",
    influence: 170,
    type: "Mélée",
    pict: "condo_gua.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 47,
    name: "Piquiers de Fortebraccio",
    influence: 235,
    type: "Piquiers",
    pict: "forte_pike.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 48,
    name: "Falconetti",
    influence: 330,
    type: "Piquiers",
    pict: "falco_gun.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 49,
    name: "Janissaires",
    influence: 190,
    type: "Armes à feu",
    pict: "janissary_main.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 50,
    name: "Azaps",
    influence: 240,
    type: "Mélée",
    pict: "azap_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 51,
    name: "Silahdars",
    influence: 320,
    type: "Mélée",
    pict: "sihl_main.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 52,
    name: "Cyphaux",
    influence: 245,
    type: "Cavalerie",
    pict: "sipahi_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 53,
    name: "Milice zykalienne",
    influence: 175,
    type: "Artilleurs",
    pict: "barc-wild-cover.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 54,
    name: "Fidèles symmachéens",
    influence: 260,
    type: "Lanciers",
    pict: "symm_stal_cover.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 55,
    name: "Paladins symmachéens",
    influence: 255,
    type: "Mélée",
    pict: "symm_pal_cover.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 56,
    name: "Siphonaros",
    influence: 330,
    type: "Lance-flammes",
    pict: "barc-narf-gua-cover.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 57,
    name: "Fils de Fenrir",
    influence: 180,
    type: "Mélée",
    pict: "sons_of_fenrir_main.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 58,
    name: "Berserkers",
    influence: 245,
    type: "Mélée",
    pict: "berserker_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 59,
    name: "Skjaldmös",
    influence: 310,
    type: "Lanciers",
    pict: "shieldmaidens_main.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 60,
    name: "Moines guerriers",
    influence: 190,
    type: "Mélée",
    pict: "cudgel_monks_main.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 61,
    name: "Vigiles grisonnants",
    influence: 240,
    type: "Lanciers",
    pict: "greyhair_garrison_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 62,
    name: "Gardes au modao",
    influence: 315,
    type: "Mélée",
    pict: "modao_battalion_main.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 63,
    name: "Lansquenets",
    influence: 175,
    type: "Arme d'hast",
    pict: "landsknechts_cover.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 64,
    name: "Eclaireurs de Liao",
    influence: 315,
    type: "Cavalerie",
    pict: "liaos_rangers_cover.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 65,
    name: "Lanciers ribauds",
    influence: 240,
    type: "Cavalerie",
    pict: "armiger_lancers_cover.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 66,
    name: "Maraudeurs",
    influence: 180,
    type: "Cavalerie",
    pict: "outriders_main.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 67,
    name: "Lanceurs de haches",
    influence: 240,
    type: "Mélée",
    pict: "axe_raiders_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 68,
    name: "Grenadiers de Shenji",
    influence: 315,
    type: "Arquebusiers",
    pict: "shenji_grenadiers_main.png",
    rarity: "golden",
    inCaserne: 0,
  },
  {
    id: 69,
    name: "Cornemuseurs",
    influence: 120,
    type: "Mélée",
    pict: "bagpipers_main.png",
    rarity: "silver",
    inCaserne: 0,
  },
  {
    id: 70,
    name: "Claymores",
    influence: 235,
    type: "Mélée",
    pict: "claymores_main.png",
    rarity: "heroic",
    inCaserne: 0,
  },
  {
    id: 71,
    name: "Veneurs",
    influence: 310,
    type: "Mélée",
    pict: "houndsmen_main.png",
    rarity: "golden",
    inCaserne: 0,
  },
]);
